name: Terraform CI/CD
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0
      - run: terraform init
      - run: terraform plan

